[project]
name = "open-r1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.6.0",
    "math-verify>=0.7.0",
    "datasets>=3.5.0",
    "torch>=2.7.0",
    "wandb>=0.19.10",
]
